### ISSUE TITLE
Attacking Energy Ghost does nothing

### ISSUE THREAD

**Issue by AnonymousPuppy** [rwtema/Dark-Menagerie#3]
Using forge .1225, a custom modpack, and dark menagerie beta 2.0. Whenever I hit an energy ghost with a sword, it doesn't take any damage. If I get a critical hit, it does show the "critical hit" text, but the energy ghost still doesn't take any damage. It just keeps on hitting you, and you can't even fight back. Also tested a bow, same result, though the arrows do bounce back off. Please look into this when you can, thank you.

**Comment by rwtema** [comment]
Intended.

You need to use an enchanted weapon (or splash potion), otherwise run away and they will naturally disappear at daybreak.

**Comment by AnonymousPuppy** [comment]
Ah, thanks for clarifying.

**Comment by rwtema** [comment]
I'll add a message or something when you try to attack it.

**Comment by AnonymousPuppy** [comment]
That would be nice, documentation on the mod is scarce, and new users(like me) may not know the special attributes of the mobs.

**Comment by Thornbrier** [comment]
A message would still be helpful.

**Comment by Treita** [comment]
Just got taken out by one. Still early game, no armor, stone sword, that fun stuff. 
No alerts or messages. Thanks for letting me know that it'll poof at day because it killed me right outside my house and I was a little concerned.
